server:
  port: 8081

spring:
  output:
    ansi:
      enable: ALWAYS
  datasource:
    url: jdbc:h2:file:D:\intelliJ_Project\kotlin-spring-API\kotlin-spring\db
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE